# Conda environment
name: vorts
channels:
  - conda-forge
dependencies:
  - python
  #
  # used by vorts
  - cycler
  - matplotlib
  - numba
  - numpy
  - scipy
  - tqdm
  - xarray
  #
  # example nbs
  - ipympl
  - jupyterlab>=3
  #
  # dev
  - pytest
  #
  # for docs
  - pip
  - pip:
    - pdoc3
