name: vorts-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  #
  # used by vorts
  - cycler
  - makefun
  - matplotlib
  - numba
  - numpy
  - scipy
  - tqdm
  - xarray
  #
  # example nbs
  - ipympl
  - jupyterlab>=3
  - jupytext
  #
  # dev
  - pytest>=6  # pyproject.toml support
  - rope
  #
  - pip
  - pip:
      #
      # for docs
      - pdoc3
      #
      # the package as an editable install
      - '-e .'
