name: Test

on:
  push:
    paths:
      - '**.py'
      - '**.f*'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}  # needed for the Conda activation to work

    steps:
      - name: Check out
        uses: actions/checkout@v2

      # TODO: This part takes multiple minutes (~3). Should replace by pip method once vorts is installable.
      - name: Install dependencies in Miniconda env and activate it
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          activate-environment: vorts
          environment-file: environment.yml

      - name: Check Conda env info
        run: |
          conda info

      - name: Build the Fortran model
        run: |
          cd vorts/f/src && make && cd $HOME

      - name: Test with pytest
        run: |
          python -m pytest
